---
name: random
version: 0.02
author:
  - 'JMELTZER <joerg@joergmeltzer.de>'
abstract: have rand() return integers or fixed values
license: perl
resources:
  license: ~
requires:
  Test::More: 0
  perl: 5.010
provides:
  random:
    file: lib/random.pm
    version: 0.02
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
